### ISSUE TITLE
Request for High BG set at 400

### ISSUE THREAD

**Issue by Bender1061** [ecc1/medtronic#11]
Not really an issue per say, but. 

One of the things I really liked about the Dev branch of Decocare was 

https://github.com/openaps/decocare/blob/dev/tests/cgm/test_event_decoding.py

Specifically what I liked was 

def test_sensor_data_low(self):
    page = self.make_into_page('06' + self.SENSOR_TIMESTAMP_REFERENCE)
    records = cgm.PagedData.Data(page).decode()
    self.assertEqual(records[0]['name'], 'GlucoseSensorDataLow')
    self.assertEqual(records[0]['date'], '2016-02-08T20:54:00')
    self.assertEqual(records[0]['sgv'], 40)

  def test_sensor_data_high(self):
    page = self.make_into_page('0007' + self.SENSOR_TIMESTAMP_REFERENCE)
    records = cgm.PagedData.Data(page).decode()
    self.assertEqual(records[0]['name'], 'GlucoseSensorDataHigh')
    self.assertEqual(records[0]['date'], '2016-02-08T20:54:00')
    self.assertEqual(records[0]['sgv'], 400)

I believe this is where the magic was happening, of when you go dreaded High or Low it would keep the CGM data at either 400 or 40. So that way OpenAPS would keep running till it finally got your Blood Sugar down or back up to a level that it would read. 

I'm I'm requesting this to happen in the go code. 

Thanks

**Comment by ecc1** [comment]
Added.
