### ISSUE TITLE
Calibrations aren't pulled from the pump

### ISSUE THREAD

**Issue by jaylagorio** [ecc1/medtronic#4]
In `0.6.2` of oref0 the scripts read finger stick calibrations out of the pump and put them in `pumphistory.json`. At the end of everything, they end up in Nightscouts as red dots.

I noticed in moving to `0.7.0` with the new Go implementations that the calibrations no longer make it up there and I think it's because the Go scripts aren't pulling the calibrations.

**Comment by alimhassam** [comment]
This might be due to the records bring skipped by openaps.jq. 
if you see the missing data by running `pumphistory` directly then simply adding the record type to your ~/myopenaps/openaps.jq should restore the functionality.

**Comment by ecc1** [comment]
No, it's a limitation in the conversion of the internal CGM history Go
structs to JSON. It's even documented :-)
https://github.com/ecc1/medtronic/blob/master/nightscout.go#L192-L194

**Comment by alimhassam** [comment]
Ah, my guess was totally wrong then, thanks for correcting me.

**Comment by ecc1** [comment]
Added support for calibrations in 93c7b414d91b657a20c83ebf2bf6dd2811317d83

**Comment by jaylagorio** [comment]
This is great, thank you! I'll test this weekend. Will I need to do a full `ore0-setup` or would this come down with a `git pull`?

**Comment by ecc1** [comment]
You should be able to just download the latest release tarball for your setup, untar it, and move all the executables to /usr/local/bin.
