### ISSUE TITLE
FEATURE REQUEST: cgmupdate calculates trend data

### ISSUE THREAD

**Issue by juehv** [ecc1/medtronic#5]
Currently we need to compute the cgmupdate results with oref0-mdt-update to add trend information. To do so we need lots for data reformatting and need to start a nodejs instance. It would be nice if cgmupdate alread calculates the trend and add the fields to its output.

**Comment by ecc1** [comment]
I have a first cut at this, but I could use some test data to validate it. If you have MDT CGM readings with the trends that are calculated by oref0-mdt-trend.js that would be helpful.

**Comment by ecc1** [comment]
I'll go ahead and push a preliminary version of this. So far, tested only against the Dexcom G4 trend algorithm, which it agrees with about 90% of the time.
